.Dd $Mdocdate: March 18 2023 $
.Dt Welcome! 7
.Os
.Sh NAME
.Nm mtboehlke.com
.Nd You have reached my bookmarks page.
.Sh Introduction
These are places around the internet that I have found especially interesting and useful.
.Sh Cool Software
.Bl -bullet
.It
.Lk https://skarnet.org/software/ skarnet.org
High quality software, including a set of general-purpose C programming libraries, the execline scripting language, and a suite of small and secure supervision utilities
.It
.Lk https://sndio.org/ sndio
A small and easy to use audio framework from OpenBSD, and also ported to NetBSD, FreeBSD, and Linux
.It
.Lk https://mandoc.bsd.lb/ mandoc
A suite of tools for compiling the mdoc semantic markup language
.It
.Lk https://litcave.rudi.ir/ LITCAVE
Home of Neatvi, a minimal vi/ex implementation that supports bidirectional UTF-8 text; also home to useful utilities for the Linux framebuffer, such as Fbpad and Fbpdf
.It
.Lk https://voidlinux.org/ "Void Linux"
The Void Linux distribution, the gateway that introduced me to most of the above
.El
.Sh Guides
.Bl -bullet
.It
.Lk https://stackoverflow.com/questions/1218390/what-is-your-most-productive-shortcut-with-vim/1220118#1220118 "Your problem with Vim is that you don't grok vi"
.It
.Lk https://ctan.org/pkg/lshort "The Not So Short Introduction to LaTeX"
.It
.Lk https://www.linuxfromscratch.org/hints/downloads/files/more_control_and_pkg_man.txt "Package Users"
A strategy for managing locally installed software using only Unix builtins
.El
